Typo fix, Event indexing & frontend tokenId support fix, better testing, Linting support & all images mime types support filter & polish!
PatrickAlphaC/hardhat-nft-fcc pull request #106
Opened 2024-01-16 08:41 UTC by theirrationalone

1. There was a few constants & variables ES6 syntax omissions -- fixed
2. Dynamic Svg minting had an event misconfig -- {tokenId log prominent for fronted} fixed
3. Now we have better images mime types support previously we had support only for png mime type.
4. Linting was missing for solidity. Added .solhint.json & .solhintignore
5. and Just enhanced some testing.

;`)

2024-01-24 20:08 UTC, PatrickAlphaC requested changes

2024-01-24 20:08 UTC, PatrickAlphaC commented on test/unit/randomIpfs.test.js
> +                              assert.equal(minter, deployer)
```suggestion
                              assert.equal(minter, deployer.address)
```

2024-01-24 20:08 UTC, merged

2024-01-24 20:09 UTC, PatrickAlphaC commented
Made one change so tests pass. Merged, thank you!

2024-01-25 00:42 UTC, theirrationalone commented
> Made one change so tests pass. Merged, thank you! 

You're welcome Ser ;`)